#ifndef _PIECE_VALUES_
#define _PIECE_VALUES_

#define UNIT_FACTOR 128

// No piece may be worth more than 127 units!
// (otherwise overflows will occur)

#define PAWN_UNITS 8
#define KNIGHT_UNITS (3*8)
#define BISHOP_UNITS (3*8+1)
#define ROOK_UNITS (5*8+3)
#define QUEEN_UNITS (9*8)
#define KING_UNITS 0

#define WPAWN_UNITS 8
#define WKNIGHT_UNITS (3*8)
#define WBISHOP_UNITS (3*8+1)
#define WROOK_UNITS (5*8+3)
#define WQUEEN_UNITS (9*8)
#define WKING_UNITS 0

#define BPAWN_UNITS (-WPAWN_UNITS)
#define BKNIGHT_UNITS (-WKNIGHT_UNITS)
#define BBISHOP_UNITS (-WBISHOP_UNITS)
#define BROOK_UNITS (-WROOK_UNITS)
#define BQUEEN_UNITS (-WQUEEN_UNITS)
#define BKING_UNITS (-WKING_UNITS)

extern const int PIECE_UNITS[13];

// i SEE_PIECE_UNITS har (fx) hvid kongen værdien SEE_WKING_UNITS
#define SEE_WKING_UNITS 127
#define SEE_BKING_UNITS -127
extern const int SEE_PIECE_UNITS[13];

#define PAWN_VALUE (UNIT_FACTOR*PAWN_UNITS)
#define KNIGHT_VALUE (UNIT_FACTOR*KNIGHT_UNITS)
#define BISHOP_VALUE (UNIT_FACTOR*BISHOP_UNITS)
#define ROOK_VALUE (UNIT_FACTOR*ROOK_UNITS)
#define QUEEN_VALUE (UNIT_FACTOR*QUEEN_UNITS)
#define KING_VALUE (UNIT_FACTOR*KING_UNITS)

extern const int ABS_PIECE_VALUES[13];

#define WPAWN_VALUE (UNIT_FACTOR*WPAWN_UNITS)
#define WKNIGHT_VALUE (UNIT_FACTOR*WKNIGHT_UNITS)
#define WBISHOP_VALUE (UNIT_FACTOR*WBISHOP_UNITS)
#define WROOK_VALUE (UNIT_FACTOR*WROOK_UNITS)
#define WQUEEN_VALUE (UNIT_FACTOR*WQUEEN_UNITS)
#define WKING_VALUE (UNIT_FACTOR*WKING_UNITS)

#define BPAWN_VALUE (UNIT_FACTOR*BPAWN_UNITS)
#define BKNIGHT_VALUE (UNIT_FACTOR*BKNIGHT_UNITS)
#define BBISHOP_VALUE (UNIT_FACTOR*BBISHOP_UNITS)
#define BROOK_VALUE (UNIT_FACTOR*BROOK_UNITS)
#define BQUEEN_VALUE (UNIT_FACTOR*BQUEEN_UNITS)
#define BKING_VALUE (UNIT_FACTOR*BKING_UNITS)

// i SEE_PIECE_VALUES har (fx) hvid kongen værdien SEE_WKING_VALUES
extern const int PIECE_VALUES[13];
#define SEE_WKING_VALUE (UNIT_FACTOR*127)
#define SEE_BKING_VALUE (UNIT_FACTOR*-127)
extern const int SEE_PIECE_VALUES[13];

#endif
