#include "piece_values.hxx"

const int PIECE_UNITS[13] =
  {0,
   WPAWN_UNITS, WKNIGHT_UNITS, WBISHOP_UNITS, WROOK_UNITS, WQUEEN_UNITS, WKING_UNITS,
   BPAWN_UNITS, BKNIGHT_UNITS, BBISHOP_UNITS, BROOK_UNITS, BQUEEN_UNITS, BKING_UNITS};

const int SEE_PIECE_UNITS[13] =
  {0,
   WPAWN_UNITS, WKNIGHT_UNITS, WBISHOP_UNITS, WROOK_UNITS, WQUEEN_UNITS, SEE_WKING_UNITS,
   BPAWN_UNITS, BKNIGHT_UNITS, BBISHOP_UNITS, BROOK_UNITS, BQUEEN_UNITS, SEE_BKING_UNITS};

const int ABS_PIECE_VALUES[13] =
  {0,
   PAWN_VALUE, KNIGHT_VALUE, BISHOP_VALUE, ROOK_VALUE, QUEEN_VALUE, KING_VALUE,
   PAWN_VALUE, KNIGHT_VALUE, BISHOP_VALUE, ROOK_VALUE, QUEEN_VALUE, KING_VALUE};

const int PIECE_VALUES[13] =
  {0,
   WPAWN_VALUE, WKNIGHT_VALUE, WBISHOP_VALUE, WROOK_VALUE, WQUEEN_VALUE, WKING_VALUE,
   BPAWN_VALUE, BKNIGHT_VALUE, BBISHOP_VALUE, BROOK_VALUE, BQUEEN_VALUE, BKING_VALUE};

const int SEE_PIECE_VALUES[13] =
  {0,
   WPAWN_VALUE, WKNIGHT_VALUE, WBISHOP_VALUE, WROOK_VALUE, WQUEEN_VALUE, SEE_WKING_VALUE,
   BPAWN_VALUE, BKNIGHT_VALUE, BBISHOP_VALUE, BROOK_VALUE, BQUEEN_VALUE, SEE_BKING_VALUE};
